# Generated by Django 4.1.13 on 2024-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_structure_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/default.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Белгісіз', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/default.jpg', null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(default='Белгісіз', max_length=100),
        ),
    ]
