# Generated by Django 5.1.2 on 2024-11-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_customer_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(blank=True, default='Белгісіз', max_length=100, null=True),
        ),
    ]
