# Generated by Django 5.1.2 on 2024-11-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_customer_last_login_alter_product_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
    ]
