# Generated by Django 4.1.13 on 2024-11-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_archivedproduct_product_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_archived',
        ),
    ]
